//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : BasicCell.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//
import java.awt.*;


public class BasicCell extends Cell
{
    public BasicCell(int x, int y , String name)
    {
        mass = 25;
        direction = new Vector(x ,y   );
        location = new Vector( x , y   );
        speed = 125 / mass;
        strategy = new StandStill();
        stepNumber = 0;
        this.name = name;
    } 

    @Override
    public void step(double deltaTime)
    {
        strategy.step(this, deltaTime);
        stepNumber--;
    }
    
    @Override
    public void draw(Graphics2D g2d)
    {
        g2d.setColor(Color.YELLOW);
        g2d.fillOval((int)location.x, (int)location.y,(int) this.mass * 2 ,(int) this.mass * 2);
        g2d.setColor(Color.BLACK);
        double x = location.x + mass;
        double y = location.y + mass;
        double theta = 0;
        
        
        if (x <= direction.x && y <= direction.y)
            theta = 360- Math.asin(Math.abs(y - direction.y) / (Math.abs(x - direction.x) + Math.abs(y - direction.y))) * 180.0 / 3.14  ;
        else if (x <= direction.x && y >= direction.y)
            theta =  Math.asin(Math.abs(y - direction.y) / (Math.abs(x - direction.x) + Math.abs(y - direction.y))) * 180.0 / 3.14 ;
	else if (x >= direction.x && y >= direction.y)
            theta = 180 - (Math.asin(Math.abs(y - direction.y) / (Math.abs(x - direction.x) + Math.abs(y - direction.y))) * 180.0 / 3.14 );
        else 
            theta = 180 + (Math.asin(Math.abs(y - direction.y) / (Math.abs(x - direction.x) + Math.abs(y - direction.y))) * 180.0 / 3.14 );
        
        g2d.translate( x ,  y ) ;
        
        g2d.rotate(Math.toRadians(-theta));
        g2d.drawLine(0,0,(int) mass, 0);
        g2d.rotate(Math.toRadians(theta));
        
        g2d.translate(-x,-y);
        
        g2d.drawString(this.name+"", (int)location.x + (int)mass, (int)location.y + (int)mass-10);//name 
        g2d.drawString(this.mass+"", (int)location.x + (int)mass, (int)location.y + (int)mass);//mass
        g2d.drawString(this.foodEaten+"-"+this.cellsSwallowed+"", (int)location.x + (int)mass, (int)location.y + (int)mass+10);//eaten food --- eaten cell
        g2d.drawString(this.strategy.getName(), (int)location.x + (int)mass, (int)location.y + (int)mass+20);
        g2d.drawString(this.stepNumber+"", (int)location.x + (int)mass, (int)location.y + (int)mass + 30);
       
        
    }

}
