//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : CellDecorator.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//



public abstract class CellDecorator extends Cell
{
    public Cell decoratedCell;
    public CellDecorator(Cell cell)
    {
        this.decoratedCell = cell;
    } 
}
