//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : Display.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;


public class Display extends JPanel 
{
    BufferedImage logo;    
    public Enviroment enviroment;
    
    public Display(Enviroment enviroment)
    {
        try 
        { 
            logo = ImageIO.read(new File("Logo.bmp"));
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.enviroment = enviroment;
    }

    @Override
    public Dimension getPreferredSize()
    {
        return new Dimension (1050,720); 
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        setBackground(Color.WHITE);
        g.drawImage(logo, 30, 440, null);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setPaint (Color.black);
        g2d.drawLine(310, 0, 310, 720);
        g2d.drawLine(0, 410, 310, 410);
       
        
        g2d.setPaint(Color.LIGHT_GRAY);
        for (int i = 310 + 36; i < 1050; i += 36) 
        {
            g2d.drawLine(i, 0, i, 1050);
        }
        for (int i = 36; i < 720; i += 36) 
        {
            g2d.drawLine(310, i, 1050, i);
        }
        
        g2d.setPaint(Color.RED);
        g2d.drawString("Step : " + enviroment.numberOfSteps, 5, 20); 
        g2d.setPaint(Color.BLACK);
        g2d.drawString("Cells : " + enviroment.numberofCells, 310 - 60, 20);
        g2d.setPaint(Color.MAGENTA);
        g2d.drawString("                                     LeaderBoard", 5, 40);
        g2d.setPaint(Color.BLUE);
        g2d.drawString("             Name      Mass  HMass   Spd   Fd  C  St", 5, 80);
        g2d.setPaint(Color.GREEN);
        g2d.drawString("             ---------       -----       -----       ----     ---   -    --", 5, 100);
        
    
        //-------------------------------------------------------
 
        int j = 120;
        for (int i = 0;i < enviroment.entities.size();i++)
        {
            enviroment.entities.get(i).draw(g2d);
            if(enviroment.entities.get(i).getClass() == BasicCell.class || enviroment.entities.get(i).getClass() == Roamer.class || enviroment.entities.get(i).getClass() == Evader.class || enviroment.entities.get(i).getClass() == Hunter.class)
            {
                Cell c = (Cell) enviroment.entities.get(i);
                String s = String.format("  %7.0f  %8.0f  %10.1f  %4d  %5d  %s",c.mass,c.mass,Math.floor(c.speed * 100) / 100,c.foodEaten,c.cellsSwallowed,c.strategy.getName());
                g2d.drawString("             " + s, 42, j);
                g2d.drawString(""+c.name, 35, j);
                j += 20;
            }
        }
        
        
    }
}    

    

 