//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : FoodFactory.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//



public abstract class FoodFactory
{
    public abstract Food createFood(Enviroment env);
}
