//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : Food.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//
import java.awt.*;



public abstract class Food extends Entity
{
    
    @Override
    public void step(double deltaTime)
    {
        
    }
    
    @Override
    public void draw(Graphics2D g)
    {
        //just to show the process of factory method/abstract factory
    }
}
