//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : LossMass.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//




public class LossMass extends StepStrategy
{
    public double losePercentage;
    public LossMass( ) 
    {
        losePercentage = 0.5;
    }

    @Override
    public String getName()
    {
        return "LM";
    }

    @Override
    public void step(Entity e, double deltaTime)
    {
        Cell c = (Cell) e;
        if(e.mass > 20)
            c.removeMass(losePercentage);
        e.speed = 125/e.mass;
    }
}
