
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : MoveLinear.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//



public class MoveLinear extends StepStrategy
{
    private Random rand  = new Random();
    private int x , y;
    public MoveLinear() 
    {
        switch (rand.nextInt(5))
        {
        case 0:
            x = 310;y = 0;
            break;
        case 1:
            x = 310;y = 720;
            break;
        case 2:
            x = 1030;y = 0;
            break;
        case 3:
            x = 1030;y = 720;
            break;
        }
    }

    @Override
    public String getName()
    {
        return "ML";
    }

    @Override
    public void step(Entity e, double deltaTime)
    {
        e.direction.x = x;
        e.direction.y = y;
        if(e.location.x >= 1030){
            x = 310;e.direction.x = x;}
        if(e.location.x <= 320){
            x = 1050;e.direction.x = x;}
        if(e.location.y+ e.mass >= 700 - e.mass){
            y = 0;e.direction.y = y;}
        if(e.location.y <= 0){
            y = 720;e.direction.y = y;}
        
        
        if(e.location.x + e.mass  < x) 
            e.location.x = e.location.x + e.speed;
        else
           e.location.x = e.location.x - e.speed;
        
        
        if(e.location.y + e.mass   < y) 
            e.location.y = e.location.y + e.speed;
        else
            e.location.y = e.location.y - e.speed;
    }
}
