//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : MoveRandom.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//

import java.util.Random;


public class MoveRandom extends StepStrategy
{
    Enviroment enviroment;
    public MoveRandom(Enviroment enviroment) 
    {
        this.enviroment = enviroment;
    }
    
    @Override
    public String getName()
    {
        return "MR";
    }

    @Override
    public void step(Entity e, double deltaTime)
    {
        Random rand = new Random();
        e.direction.x = rand.nextInt(741) + 310;
        e.direction.y = rand.nextInt(721);
        
        
        if(e.location.x + e.mass  < e.direction.x) 
            e.location.x = e.location.x + e.speed;
        else
           e.location.x = e.location.x - e.speed;
        
        
        if(e.location.y + e.mass   < e.direction.y) 
            e.location.y = e.location.y + e.speed;
        else
            e.location.y = e.location.y - e.speed;
    }
    @Override
    public boolean isFinished()
    {
        return false;
    }
}
