//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : Organism.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//
import java.awt.Color;
import java.awt.Graphics2D;


public class Organism extends Food
{
    public double radius;
    
    public Organism(int x , int y , double radius , Color color)
    {
        location = new Vector( x , y);
        direction = new Vector(x,y);
        this.radius = radius;
        this.color = color;
        speed = 0.3;
        strategy = new StandStill();
        stepNumber = 0;
    }
    @Override
    public void step(double deltaTime)
    {
        strategy.step(this, deltaTime);
        stepNumber--;
    }
    @Override
    public void draw(Graphics2D g2d)
    {
        g2d.setColor(color);
        g2d.fillOval( (int)location.x, (int)location.y , (int)radius , (int)radius );
    }
    
    
}
