
import java.awt.Color;
import java.awt.Graphics2D;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : Plasma.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
public class Plasma extends Food
{
    public double radius;
    
    public Plasma(int x , int y , double radius)
    { 
        location = new Vector( x , y);
        direction = new Vector( x , y);
        this.radius = radius;
        strategy = new StandStill();
        stepNumber = 0;
        speed = 5;
        
    }
    @Override
    public void step(double deltaTime)
    {
        strategy.step(this, deltaTime);
        stepNumber--;
    }
    @Override
    public void draw(Graphics2D g2d)
    {
        g2d.setColor(Color.RED);
        g2d.fillOval( (int)location.x, (int)location.y , (int)radius , (int)radius );
    }
}
