

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : PlasmaFactory.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//

public class PlasmaFactory extends FoodFactory
{
    @Override
    public Food createFood(Enviroment env)
    {
        return new Plasma(0,0,0);
    }
}
