//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : Roamer.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//
import java.awt.Color;
import java.awt.Graphics2D;



public class Roamer extends CellDecorator
{
    public Cell cell;
    public Roamer(Cell cell)
    {
        super(cell);
        this.cell = cell;
        mass = cell.mass;
        
        speed = 125 / mass;
        direction = new Vector( cell.location.x  ,cell.location.y  );
        location = new Vector( cell.location.x , cell.location.y  );
        this.name = cell.name;
        
        strategy = cell.strategy;
        stepNumber = cell.stepNumber;
        
        this.foodEaten = cell.foodEaten;
        this.cellsSwallowed = cell.cellsSwallowed;
     
    }
    
    @Override
    public void step(double deltaTime)
    {
        strategy.step(this, deltaTime);
        stepNumber--;
    }

    @Override
    public void draw(Graphics2D g2d)
    {
        //draw Roamer
        g2d.setColor(Color.GREEN);
        g2d.fillOval((int)location.x , (int)location.y ,(int) mass*2 ,(int) mass*2);
        g2d.setColor(Color.BLACK);
        
        
        double x = location.x + mass;
        double y = location.y + mass;
        double theta = 0;
        
        
        if (x <= direction.x && y <= direction.y)
            theta = 360- Math.asin(Math.abs(y - direction.y) / (Math.abs(x - direction.x) + Math.abs(y - direction.y))) * 180.0 / 3.14  ;
        else if (x <= direction.x && y >= direction.y)
            theta =  Math.asin(Math.abs(y - direction.y) / (Math.abs(x - direction.x) + Math.abs(y - direction.y))) * 180.0 / 3.14 ;
	else if (x >= direction.x && y >= direction.y)
            theta = 180 - (Math.asin(Math.abs(y - direction.y) / (Math.abs(x - direction.x) + Math.abs(y - direction.y))) * 180.0 / 3.14 );
        else 
            theta = 180 + (Math.asin(Math.abs(y - direction.y) / (Math.abs(x - direction.x) + Math.abs(y - direction.y))) * 180.0 / 3.14 );
        
        
        g2d.translate( x ,  y ) ;
        
        
        g2d.rotate(Math.toRadians(-theta));
        g2d.drawLine(0,0,(int) mass, 0);
        g2d.rotate(Math.toRadians(theta));
        
        g2d.translate(-x,-y);
        
        
        g2d.drawString(this.name+"", (int)location.x + (int)mass, (int)location.y + (int)mass-10);//name 
        g2d.drawString(this.mass+"", (int)location.x + (int)mass, (int)location.y + (int)mass);//mass
        g2d.drawString(this.foodEaten+"-"+this.cellsSwallowed+"", (int)location.x + (int)mass, (int)location.y + (int)mass+10);//eaten food --- eaten cell
        g2d.drawString(this.strategy.getName(), (int)location.x + (int)mass, (int)location.y + (int)mass+20);
        g2d.drawString(this.stepNumber+"", (int)location.x + (int)mass, (int)location.y + (int)mass + 30);
    }
	
}
