//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : StandStill.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//



public class StandStill extends StepStrategy
{
    public StandStill() 
    {
        //just stand
    }

    @Override
    public String getName()
    {
        return "SS";
    }

    @Override
    public void step(Entity e, double deltaTime)
    {
        
    }
    
    @Override
    public boolean isFinished()
    {
        return true; 
    }
	
}
