//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : StepStrategy.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//



public abstract class StepStrategy
{
    public boolean isFinished()
    {
        return true; 
    }
    public abstract String getName();
    public abstract void step(Entity e, double deltaTime);
}
