//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agarion
//  @ File Name : Sugar.java
//  @ Date : 11/07/2015
//  @ Author : Ali Abbasi
//
//
import java.awt.Color;
import java.awt.Graphics2D;



public class Sugar extends Food
{
    public int sideHalfLength;
    public int angel;
    
    public Sugar(int x, int y, int sideHalfLength, Color color,int angel)
    {
        location = new Vector( x , y);
        direction = new Vector( x , y);
        this.sideHalfLength = sideHalfLength;
        this.color = color;
        strategy = new StandStill();
        stepNumber = 0;
    }
    @Override
    public void draw(Graphics2D g2d)
    {
        g2d.setColor(color);
        g2d.drawRect((int)location.x, (int)location.y, sideHalfLength, sideHalfLength);
        
    }
    @Override
    public void step(double deltaTime)
    {
        strategy.step(this, deltaTime);
        stepNumber--;
    }
    
    
}
